Account configuration - Issue ID = 2
wwi21seb-projekt/server-alpha pull request #13
Opened 2024-01-07 14:08 UTC by AdrianHagen

# Pull Request

## Trello Ticket

- [Trello Ticket Link](https://trello.com/c/zik6TGN5/30-id-2-als-nutzer-m%C3%B6chte-ich-meinem-account-konfigurieren-k%C3%B6nnen-passwort-%C3%A4ndern-nickname-%C3%A4ndern)
  

## Description

Added two endpoints  for Changing the users nickname and password
Extracted functionallity to check password to seperate function

2024-01-07 16:25 UTC, 930C reviewed
Alles sieht soweit okay aus, würde aber trotzdem gerne das "PATCH {username}/nickname" mit "`PUT {username}`" ersetzen, da wir dies so in Postman definiert hatten.

2024-01-07 20:56 UTC, Frecherenkel60 commented
> Alles sieht soweit okay aus, würde aber trotzdem gerne das "PATCH {username}/nickname" mit "`PUT {username}`" ersetzen, da wir dies so in Postman definiert hatten.

Die Postman-Doku sieht:

... `POST /users` für das Passwort vor
... `PUT /users` für Nickname und Status

Also nicht in beiden Fällen Post wie gerade

2024-01-07 21:07 UTC, Frecherenkel60 requested changes
Guter Anfang, aber paar Sachen stimmen noch nicht ganz. 😅

2024-01-07 21:07 UTC, Frecherenkel60 commented on internal/routing/router.go
> +		r.Post("/{username}/password", userHdl.ChangePassword)
Wie im vorigen Kommentar, das bitte ändern zu:

```go
r.Put("/users", userHdl.ChangeNicknameAndStatus)
r.Patch("/users", userHdl.ChangePassword)
```

Die entsprechende Dokumentation siehst du in [Postman](https://app.getpostman.com/join-team?invite_code=47970e6341f3956a182e9a0aea00a2e6&target_code=2e812c98237d3e1ecd1a1fb88a66edb2).

Als Erklärung:

- Wir differenzieren nicht mit `nickname` und `password` die Endpunkte, sondern anhand der Methoden. Da `POST /users` schon mit der Registrierung belegt ist und auch iwie nicht zu REST passt, benutzen wir `PATCH /users` für password-only und `PUT /users` für alle anderen Informationen. Alle anderen Informationen bezieht sich momentan nur auf Nickname und Status.
- `{username}` als Path-Parameter brauchen wir nicht, da das ja ein autorisierter Endpunkt ist und wir die Information über den `JWT` kriegen.

2024-01-07 21:07 UTC, Frecherenkel60 commented on internal/routing/handlers/user_handler.go
> +	queryString := "SELECT password, user_id FROM alpha_schema.users WHERE username = $1"
Da du die `user_id` in der Methode nicht verwendest, kannst du das aus der Query hier streichen.

2024-01-07 21:07 UTC, Frecherenkel60 commented on internal/routing/handlers/user_handler.go
> +	}
Einmal die Reihenfolge ändern bitte. Zuerst den Body in die Response encoden und dann den `StatusOK`-Header setzen.

2024-01-07 21:07 UTC, Frecherenkel60 commented on internal/routing/handlers/user_handler.go
> +}
Hier bitte auch die Reihenfolge ändern von Encoding und Header setzen.

2024-01-07 21:07 UTC, Frecherenkel60 commented on internal/schemas/dto_schema.go
> +	NewPassword string `json:"new_password" validate:"required,min=8,password_validation"`
Postman sieht folgenden Body vor:

```json
{
    "oldPassword": "...",
    "newPassword": ""
}
```

Also hier bitte noch bei `json` camel-casen.

2024-01-07 21:07 UTC, Frecherenkel60 commented on internal/schemas/dto_schema.go
> +}
Das ist laut Postman ja `ChangeTrivialInformation`, braucht also im Moment Nickname und Status. So unter Postman dokumentiert:

```json
{
    "nickname": "", // always give full information, even when not changing
    "status": ""    // always give full information, even when not changing
}
```

2024-01-07 21:10 UTC, Frecherenkel60 commented
Kannst du nach den obigen Kommentaren noch die Pipeline-Issues angucken? Sind glaub nur Formattierungs-Sachen

2024-01-13 12:49 UTC, Frecherenkel60 reviewed
Noch die letzte Änderung, dann sind wir good to go. 👍🏽

2024-01-13 12:49 UTC, Frecherenkel60 commented on internal/routing/handlers/user_handler.go
> +	}
Brauchst du nicht, wenn das `UPDATE`-Statement oben erfolgreich durchläuft, kannst du einfach die Werte aus dem Request-Body nehmen.

2024-01-13 13:30 UTC, Frecherenkel60 approved these changes
LGTM

2024-01-13 14:02 UTC, merged