Feature/docker management
wwi21seb-projekt/server-alpha pull request #2
Opened 2023-12-28 01:37 UTC by 930C

# Pull Request

## Trello Ticket

- [Trello Ticket Link](insert link here)
  

## Description

## Additional Remarks

2023-12-28 12:56 UTC, Frecherenkel60 requested changes

2023-12-28 12:56 UTC, Frecherenkel60 commented on build/package/Dockerfile
> +WORKDIR /go/app
Wofür das hier? Würde das jetzt im Endeffekt nicht den späteren Copy-Befehl in /go/app/go/app setzen?

2023-12-28 12:56 UTC, Frecherenkel60 commented on deployments/docker-compose.yml
> +    image: "server-alpha:latest"
Könnten wir theoretisch auch vom GitHub-Container Registry ziehen, oder?

2023-12-28 12:56 UTC, Frecherenkel60 commented on deployments/server_alpha_db.sql
> +CREATE SCHEMA alpha_schema;
Schema muss v1 heißen, sonst funktioniert der gesamte Code nicht. Können es aber auch im Code renamen, wenn es dir so lieber ist

2023-12-28 12:56 UTC, Frecherenkel60 commented on deployments/server_alpha_db.sql
> +	expires_at date,
Wir benutzen kein Date, das ist zu ungenau, da es nur den Tag datiert. Um ganz genau zu sein wie abgesprochen in der Vorlesung, brauchen wir timestamptz, also nen Timestamp mit Timezone. Unten im Schema dann genauso

2023-12-28 12:56 UTC, Frecherenkel60 commented on internal/managers/jwt_manager.go
> +	}
Ich versteh nicht ganz wieso du das alles jetzt geändert hast, gabs einen Grund dafür?

2023-12-28 17:22 UTC, Frecherenkel60 approved these changes
`setup_env` ist nice, ty dafür :)

2023-12-28 17:22 UTC, Frecherenkel60 commented on README.md
> +# Getting Started
Schreiben wir dann die Tage zusammen das HowTo?

2023-12-28 17:22 UTC, Frecherenkel60 commented on deployments/docker-compose.prod.yml
> +    image: "${SERVER_IMAGE:-ghcr.io/wwi21seb-projekt/server-alpha:main}"
Funktioniert das oder brauchen wir nen Personal Access Token mit Rechten?

2023-12-28 23:59 UTC, 930C commented on README.md
> +# Getting Started
Jo

2023-12-29 11:17 UTC, 930C commented on deployments/docker-compose.prod.yml
> +    image: "${SERVER_IMAGE:-ghcr.io/wwi21seb-projekt/server-alpha:main}"
`docker pull ghcr.io/wwi21seb-projekt/server-alpha:main` klappt auf meinem Server ohne Access Tokens, denke also nicht

2023-12-29 12:08 UTC, merged