Comments
wwi21seb-projekt/server-alpha pull request #74
Opened 2024-05-20 19:56 UTC by abramsmax

# Pull Request

## Trello Ticket

Comments for posts

## Description

Functionality for creating and getting comments

2024-05-21 08:48 UTC, 930C commented on internal/handlers/post_handler.go
> +	tx := utils.BeginTransaction(ctx, handler.DatabaseManager.GetPool())
Ich denke wir brauchen keine Transkation für das fetchen von Comments

2024-05-21 10:23 UTC, Frecherenkel60 approved these changes
```sql
-- object: alpha_schema.comments | type: TABLE --
-- DROP TABLE IF EXISTS alpha_schema.comments CASCADE;
CREATE TABLE alpha_schema.comments (
	comment_id uuid NOT NULL,
	content varchar(128) NOT NULL,
	created_at timestamptz NOT NULL,
	author_id uuid NOT NULL,
	post_id uuid NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (comment_id)
);

ALTER TABLE alpha_schema.comments ADD CONSTRAINT posts_fk FOREIGN KEY (post_id)
REFERENCES alpha_schema.posts (post_id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE alpha_schema.comments ADD CONSTRAINT users_fk FOREIGN KEY (author_id)
REFERENCES alpha_schema.users (user_id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --
```

Hier noch eine passende Relation für Kommentare

2024-05-21 10:23 UTC, krieger2501 commented on deployments/docker-compose.yml
> +        - "./keys:${KEYS_DIR:-/keys}"
irgendein tieferer sinn hier?

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +	}
Braucht man nicht, beim `Insert` vom Comment kommt ein Fehler zurück, wenn der Post nicht existiert, das kann man abfangen.

Hier ne Beispielantwort aus pgAdmin mit falscher `post_id`:

```
ERROR:  Key (post_id)=(476ad0d1-3c34-49f0-a96c-4ef287780a20) is not present in table "posts".insert or update on table "comments" violates foreign key constraint "posts_fk" 

ERROR:  insert or update on table "comments" violates foreign key constraint "posts_fk"
SQL state: 23503
Detail: Key (post_id)=(476ad0d1-3c34-49f0-a96c-4ef287780a20) is not present in table "posts".
```

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +	_, err = tx.Exec(ctx, queryString, queryArgs...)
Braucht das nicht so kompliziert zu machen, ich hatte das bei paar Dingern nur so kompliziert, weil wir bedingte Sachen hatten wie Location. Hier ist ja alles straightforward, da braucht ihr die Extravariablen nicht und könnt alles über `queryString` und `tx.Exec` direkt benutzen.

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +	tx := utils.BeginTransaction(ctx, handler.DatabaseManager.GetPool())
+1, haben ja keine Mutations auf der Datenbank

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +
nit: keine leerzeile nach methodenbeginn

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +    `
```suggestion
        LIMIT $2 OFFSET $3`
```

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +	}
Wir haben ein DTO für PaginationObjekte, das könnt ihr benutzen.

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/managers/jwt_manager.go
> +		keysDir = ".keys" // Default keys directory
Das macht keinen Sinn

2024-05-21 10:23 UTC, Frecherenkel60 commented on internal/schemas/dtos.go
> +}
Warum habt ihr hier zwei Structs? Eine reicht doch vollkommen, da sich die Rückgabestruktur nicht ändert. Siehe Postman:

```json
{
    "commentId": "",
    "content": "text", // 128 Zeichen
    "author": {
            "username": "test2",
            "nickname": "",
            "profilePictureURL": ""
    },
    "creationDate": "2024-02-01T16:18:48+01:00"
}
```

2024-05-21 10:23 UTC, Frecherenkel60 requested changes
```sql
-- object: alpha_schema.comments | type: TABLE --
-- DROP TABLE IF EXISTS alpha_schema.comments CASCADE;
CREATE TABLE alpha_schema.comments (
	comment_id uuid NOT NULL,
	content varchar(128) NOT NULL,
	created_at timestamptz NOT NULL,
	author_id uuid NOT NULL,
	post_id uuid NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (comment_id)
);

ALTER TABLE alpha_schema.comments ADD CONSTRAINT posts_fk FOREIGN KEY (post_id)
REFERENCES alpha_schema.posts (post_id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE alpha_schema.comments ADD CONSTRAINT users_fk FOREIGN KEY (author_id)
REFERENCES alpha_schema.users (user_id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --
```

Hier noch eine passende Relation für Kommentare

2024-05-22 07:29 UTC, 930C approved these changes

2024-05-22 07:48 UTC, Frecherenkel60 approved these changes

2024-05-22 07:48 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +		if ok && pgErr.Code == "23503" { // 23503 is the error code for foreign key violation
Könntet aus Nils seinem PR auch die Error-Konstanten von PG benutzen. Wäre dann mit der Methode: `IsIntegrityConstraintViolation` glaub ich.

2024-05-22 07:48 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +	queryString = "SELECT username, nickname FROM alpha_schema.users WHERE user_id = $1"
In Postman ist auch noch die `profilePictureUrl` definiert.

2024-05-22 07:48 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +        LIMIT $2 OFFSET $3`
nice 👍🏽

2024-05-22 07:48 UTC, Frecherenkel60 commented on internal/handlers/post_handler.go
> +		var commentId uuid.UUID
Bin mir recht sicher, dass man die UUID direkt in nen String scannen kann.

2024-05-23 13:12 UTC, merged